### ISSUE TITLE
validate method - syntactic sugar

### ISSUE THREAD

**Issue by bigpresh** [LoonyPandora/Dancer-Plugin-Bcrypt#1]
I think it's missing a convenience keyword like `bcrypt_validate()` which just takes a plain text password entered and a stored hash, and returns a boolean to indicate whether the plain text password matches.  That would seem to make sense to me :)

**Comment by LoonyPandora** [comment]
Nice idea, would be an easy thing to add.

**Comment by bigpresh** [comment]
Indeed - in fact, added in the pull request I just sent :)
