### ISSUE TITLE
Should `bcrypt()` be e.g. `bcrypt_hash()` ?

### ISSUE THREAD

**Issue by bigpresh** [LoonyPandora/Dancer-Plugin-Bcrypt#5]
I wonder whether the `bcrypt()` keyword should actually be e.g. `bcrypt_hash()`, so it's not too generic, and is clearer as to what it does?

**Comment by LoonyPandora** [comment]
I think bcrypt is obvious enough, I followed the pattern of Digest::SHA / MD5 - their functions are called just sha1 and md5.

Reason to change the name would be if someone used the module I've wrapped, and pulls in it's version of the bcrypt keyword. I'd imagine that would cause some issues...

**Comment by bigpresh** [comment]
Fair enough :)
