### ISSUE TITLE
Support other hashing schemes -> More generic plugin.

### ISSUE THREAD

**Issue by LoonyPandora** [LoonyPandora/Dancer-Plugin-Bcrypt#6]
I have been thinking about making this a more generic plugin with modules for arbitrary hashing schemes. Dancer::Plugin::Password -> With bcrypt the recommended scheme, but supporting others (so people can decode old school SHA / MD5 / Whatever)

Something like:

```
my $hash = generate_password_hash(
    scheme => 'bcrypt',
    salt   => 'blah',
    plaintext => 'password_goes_here'
);
```

Has this been done somewhere before, I imagine it must have been.

**Comment by bigpresh** [comment]
I don't recall seeing a plugin like this.

I'd go for something like Dancer::Plugin::HashPassword or something, with the scheme read from the config (probably defaulting to bcrypt), and callable either with the plaintext and salt, or just the plaintext, with suitable random salt generated for you (much like `Crypt::SaltedHash` does).

In fact, this is starting to sound more like a convenience wrapper around `Crypt::SaltedHash` :)

**Comment by LoonyPandora** [comment]
`Crypt::SaltedHash` looks interesting, and it led me to `Authen::Passphrase` which I think I will turn this module into a wrapper of - with the random salt and all that jazz.

Will work on this when I have a bit of time :)
